const ANGLES = {
  RIGHT: 90,
  LEFT: -90,
  UP: 0,
  DOWN: -180,
};

const TILES = {
  METAL: 'm',
  BOX: 'b',
  EMPTY: '',
  EXPLOADABLE: 2,
  CLEAR: 0,
  BLOCKING: 1,
  SIZE: 64,
};

const CONSTS = {
  UNIT_SIZE: 58,
  BLOCK_BOUNDARY_LEFT: 62,
  BLOCK_BOUNDARY_RIGHT: 900,
  BLOCK_BOUNDARY_TOP: 574,
  BLOCK_BOUNDARY_BOTTOM: 62,
};

const LAYOUT = {
  LEFT_MARGIN: 35,
  RIGHT_MARGIN: 925,
  TOP_MARGIN: 35,
  BOTTOM_MARGIN: 685,
  RIGHT_MARGIN: 925,
  SPACE_UNIT: 45,
};

const PLAYERS = {
  COLORS: ['#3A9DEB', '#43865D', '#AE7A1E', '#FFF867'],
};
